import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/ui/navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-mono antialiased flex-1 p-8 min-h-screen transition-all duration-300 ml-8`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}



// const Layout: React.FC = ({ children }) => {
//     return (
//         <div className="flex">
//             <Sidebar />
//             <main className="flex-1 p-8 bg-gray-100 min-h-screen transition-all duration-300" style={{ marginLeft: '4rem' }}>
//                 {children}
//             </main>
//         </div>
//     );
// };